# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1958430183a9d2e86b63333d7f3021152f84bd2237155a7eeaa45d0545fd38133f1ab8b42bf73e2012c6160a49f01c3c739317e125f15b6d3ac0300a3705517c

test:
  secret_key_base: a3912ff5981b1ccf8642e3637f1eb333694ae38607d4e9f6acb61b43893991658dd0ca28830864e2f51f6b1ed52c414bd227796870addef958a5831037e093c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
